### ISSUE TITLE
Great Work

### ISSUE THREAD

**Issue by lingdu0001** [chendong0120/cordova-heytz-yzs#1]
Thank you for you great work！ I will try this on my project

**Comment by chendong0120** [comment]
THK !  If you have any questions you can give me a message.

**Comment by lingdu0001** [comment]
I use "cordova plugin add https://github.com/chendong0120/cordova-heytz-yzs.git --variable APP_KEY=*****   --variable APP_SECRET=**** ".
But got "Error: Failed to fetch plugin https://github.com/chendong0120/cordova-heytz-yzs.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL."
I have tried on both windows and Mac. 
Would you please provide some ReadMe?  How to install it ,and how to use it? Thank you!

**Comment by chendong0120** [comment]
updated readme

**Comment by lingdu0001** [comment]
It looks like you missed packge.json,so it cannot be installed by cordova plugin add.

![image](https://user-images.githubusercontent.com/5213652/32534274-d1f4ae70-c48f-11e7-87ea-cdb402a26c48.png)

**Comment by chendong0120** [comment]
THK，After i added packages, it works. 
You can .
`    cordova plugin add https://github.com/chendong0120/cordova-heytz-yzs.git --variable APP_KEY=APP_KEY --variable APP_SECRET=APP_SECRET --variable  NSMicrophoneUsageDescription=使用麦克风 --variable NSLocationAlwaysUsageDescription=访问位置
`

**Comment by chendong0120** [comment]
I use this plugin to complete a demo and if you need anything else. I can add it when i'm free.

**Comment by lingdu0001** [comment]
OK  ,I installed it but failed to run it.
Would you please help me to fix it when you are free? Thank you !
![image](https://user-images.githubusercontent.com/5213652/32584550-ce6e4b22-c533-11e7-99dd-427163f0de41.png)

**Comment by chendong0120** [comment]
Do not use the simulator , only use the device.

**Comment by lingdu0001** [comment]
I even can't build it... so i cant use device to run it.

**Comment by lll516320921** [comment]
I met the same problem as lingdo0001,can you help us if you have time? thank you
